// <auto-generated />
using System;
using CourseLawProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseLawProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231225194955_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CourseLawProject.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CourseLawProject.Data.Entities.Admin", b =>
                {
                    b.HasBaseType("CourseLawProject.Data.Entities.User");

                    b.Property<int?>("AccessMode")
                        .HasColumnType("int");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("CourseLawProject.Data.Entities.Client", b =>
                {
                    b.HasBaseType("CourseLawProject.Data.Entities.User");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("CourseLawProject.Data.Entities.Individual", b =>
                {
                    b.HasBaseType("CourseLawProject.Data.Entities.Client");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("RNOKPP")
                        .HasColumnType("bigint");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Individuals", (string)null);
                });

            modelBuilder.Entity("CourseLawProject.Data.Entities.LegalEntity", b =>
                {
                    b.HasBaseType("CourseLawProject.Data.Entities.Client");

                    b.Property<int>("CodeEDRPOU")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationForm")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("LegalEntities", (string)null);
                });

            modelBuilder.Entity("CourseLawProject.Data.Entities.Admin", b =>
                {
                    b.HasOne("CourseLawProject.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("CourseLawProject.Data.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseLawProject.Data.Entities.Client", b =>
                {
                    b.HasOne("CourseLawProject.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("CourseLawProject.Data.Entities.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseLawProject.Data.Entities.Individual", b =>
                {
                    b.HasOne("CourseLawProject.Data.Entities.Client", null)
                        .WithOne()
                        .HasForeignKey("CourseLawProject.Data.Entities.Individual", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseLawProject.Data.Entities.LegalEntity", b =>
                {
                    b.HasOne("CourseLawProject.Data.Entities.Client", null)
                        .WithOne()
                        .HasForeignKey("CourseLawProject.Data.Entities.LegalEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
